FROM devopsfaith/krakend

COPY krakend.tmpl /etc/krakend/krakend.tmpl
COPY symmetric.json /etc/krakend/symmetric.json
COPY templates/ /etc/krakend/config/templates/
COPY settings/ /etc/krakend/config/settings/


EXPOSE 8080