version: "3"

services:
  krakend:
    environment:
      - FC_ENABLE=1
      - FC_PARTIALS=/etc/krakend/config/partials
      - FC_SETTINGS=/etc/krakend/config/settings/dev
      - FC_TEMPLATES=/etc/krakend/config/templates
    build:
      context: .
      dockerfile: Dockerfile
    command: ["run", "-dc", "krakend.tmpl"]
    ports:
      - "8080:8080"
    networks:
      - canva

networks:
  canva: { driver: bridge }
